alias cuke="cucumber -f pretty -r features/support -r features/step_definitions"
alias sc="script/console"
alias t="touch tmp/restart.txt"
alias r2="sed -i '' 's/adapter: mysql2$/adapter: mysql/g' config/database.yml config/vanity.yml"
alias r3="sed -i '' 's/adapter: mysql$/adapter: mysql2/g' config/database.yml config/vanity.yml"
