alias be="bundle exec"
alias rdb="rake db:migrate"
alias rdbt="rake db:migrate && rake db:test:prepare"
alias rc="spring rails c"
alias rg="spring rails g"
alias rgm="spring rails g migration"
alias rs="spring rspec"
